"""Add current_exchange_rate to tenants

Revision ID: 6ba0de7197c7
Revises: 604cfd96921d
Create Date: 2026-07-02 22:44:44.611511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ba0de7197c7'
down_revision: Union[str, Sequence[str], None] = '604cfd96921d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('current_exchange_rate', sa.Numeric(precision=12, scale=4), server_default=sa.text('36.50'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'current_exchange_rate')
    # ### end Alembic commands ###
