"""Add commission and seller fields

Revision ID: e5da785414e0
Revises: 6ba0de7197c7
Create Date: 2026-07-02 22:58:15.359496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5da785414e0'
down_revision: Union[str, Sequence[str], None] = '6ba0de7197c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('seller_id', sa.UUID(), nullable=True))
    op.add_column('sales', sa.Column('commission_amount_usd', sa.Numeric(precision=12, scale=4), server_default=sa.text('0'), nullable=False))
    op.create_foreign_key(None, 'sales', 'users', ['seller_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'commission_rate')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'commission_amount_usd')
    op.drop_column('sales', 'seller_id')
    # ### end Alembic commands ###
